spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookbyte
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
upload:
  directory: "C:\Users\Mateja\Desktop\CookByte\frontend\src\assets\user-uploaded-images"